/users:
  get:
    description: Retrieve all users
    responses: 
          200:
            body:
              application/json:
                example:  |
                  {
                    uname: "Raj",
                    role: "admin"
                  }
                  